### ISSUE TITLE
[Mod Support Request] 

### ISSUE THREAD

**Issue by DarkkRevenant** [glisco03/numismatic-overhaul#100]
_**VillagersPlus**_ - https://modrinth.com/mod/villagersplus
Adds 4 new villagers - Horticultist, Occultist, Oceanographer, Alchemist

_**Update: this already works thanks to Heracles code**_
_**Heracles**_ - https://modrinth.com/mod/heracles 
A new questing mod similar to FTB Quests, but not meant exclusively for FTB modpacks.
It would be awesome to be able to integrate rewards as coin payouts.

**Comment by BasiqueEvangelist** [comment]
> It would be awesome to be able to integrate rewards as coin payouts.

Can't you just reward the player with a money bag?

**Comment by DarkkRevenant** [comment]
I am uncertain of that, I will look into it.

**Comment by DarkkRevenant** [comment]
Update: Heracles already supports the mod, due to how it is coded!

**Comment by gliscowo** [comment]
In regards to VillagersPlus, I don't think there's a ton we can do aside from implementing specific modifications to their code. 

The mod has its own data-driven system for configuring the trades of their Villagers. This implementation completely bypasses Fabric's proper system for registering villager trades and thereby also bypasses Numismatic's mechanism for converting their trades into Numismatic currency.

As such, it would presumably be more productive to make an issue with them and ask them to use the `TradeOfferHelper`, which should resolve this problem without any further changes required.

Cheers
