### ISSUE TITLE
Make Coin Purse Position not bound to Recipe Button - Incompat with RecipeRemover

### ISSUE THREAD

**Issue by xR4YM0ND** [glisco03/numismatic-overhaul#102]
I changed the position of the Recipe Button via the mod RecipeRemover.

Then i noticed that the Coin Purse Pos is bound to that Button ^^

When i'm in Creative Inventory or other screens, the Coin Purse is all over there now.

**Comment by Noaaan** [comment]
Should be fixed as of ff42d763ecd3280aaf1d730ecb8119c107cf1cbd
