### ISSUE TITLE
[1.19.2] Messes with tetra trade loot pool

### ISSUE THREAD

**Issue by DoctorMage** [glisco03/numismatic-overhaul#105]
https://github.com/dr3ams/Life-in-the-village-3/issues/76

Get villager of certain type to max level and no tetra scrolls will be offered

Not an expert with code but this seems to be the handler for what villagers give no idea to tell wether its guranteed or not
https://github.com/mickelus/tetra/blob/1.18/src/main/java/se/mickelus/tetra/trades/TradeHandler.java

Mods Involved

mutil-1.19.2-5.1.0.jar
numismaticoverhaul-1.19.2-1.0.4.jar
tetra-1.19.2-5.5.1.jar

Forge 43.2.6

If this is not the correct place to report it I'll move it to tetra github

**Comment by Noaaan** [comment]
The Forge port of Numismatic Overhaul is not maintained by us. Please report it to the correct developers: https://github.com/Nyfaria/numismatic-overhaul-reforged#issues

**Comment by DoctorMage** [comment]
Apologies was not paying attention
