### ISSUE TITLE
Causes EMI to not load(Solved - NOT Numismatic problem)

### ISSUE THREAD

**Issue by Nchard** [glisco03/numismatic-overhaul#106]
Tried adding this to my server and it causes the EMI to not load on clients. Works fine in singleplayer. Look near the very end of the logs for the error

[withnumismatic.log](https://github.com/wisp-forest/numismatic-overhaul/files/12841870/withnumismatic.log)
[withoutnumismatic.log](https://github.com/wisp-forest/numismatic-overhaul/files/12841871/withoutnumismatic.log)

**Comment by BasiqueEvangelist** [comment]
Could you try installing [XL Packets](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric)? I'm a bit confused about what actually causes the disconnect (server log doesn't have any smoking gun), but it seems to be because the recipe sync packet is too large

**Comment by Nchard** [comment]
You're right, it was a simple packet size error which this mod just happened to go over.

I installed Extra Thicc Packets(a port of the outdated XL Packets) and everything seems to be working fine.
