### ISSUE TITLE
Crashes with MC Dungeons Enchantments mod

### ISSUE THREAD

**Issue by Davithy** [glisco03/numismatic-overhaul#109]
Just going off the crash report, there seems to be a mouseClicked event handler error when running Numismatic alongside the MCDE mod. The crash occurs as the game loads Singleplayer to create a new world.

A link to the crash log: [](https://mclo.gs/HZOWFU2)

**Comment by gliscowo** [comment]
Given that the mentioned link to a crash log is conspicuously missing, this is far too little information to even begin debuggin this. Please fix your initial comment or send us the crash log some other way so we can start investigating

**Comment by Davithy** [comment]
Sorry about that! I didn't expect the link to disappear. I'll go ahead and just provide the crash report file directly. This is a fresh one with MCDE 1.5.3.1 and Numismatic overhaul 0.2.10 on Minecraft version 1.20.2. Same situation, crash occurs when creating a new world. (this includes owo-lib 0.11.3, sodium 0.5.3, mod menu 8.0.0, and fabric api 0.90.4. To cover all bases, this issue persists even after removing sodium and mod menu.)

[crash-2023-10-29_17.44.33-client.txt](https://github.com/wisp-forest/numismatic-overhaul/files/13199725/crash-2023-10-29_17.44.33-client.txt)

**Comment by gliscowo** [comment]
From reading this crash report (and my own testing to confirm my suspicion) I can tell you with certainty that this is completely unrelated to Numismatic - this version of MCDE is simply incompatible with 1.20.2. 

Numismatic happens to trigger the issue quite early by loading the game's villager internals, but you can cause the exact problem just as well by making a fresh install with only MCDE and spawning a Villager. As such, you might wanna report it to them instead

Cheers

**Comment by Davithy** [comment]
Tested it myself, and left disappointed that the mod was mislabeled on both curseforge and modrinth, but happy to see that it's no fault of numismatic's. Sorry about that, but thanks for giving it the look over and understanding the issue! I'll look into taking it up with them as you suggested.
