### ISSUE TITLE
I found that the trading currency of other mods is still "Emerald". How can I change it to the currency in Numismatic Overhaul?

### ISSUE THREAD

**Issue by wsxiya** [glisco03/numismatic-overhaul#114]
Because I'm just a player and don't know how to modify it, or can you recommend some mods that modify transactions? Or is there a sample packet? Thanks

**Comment by Noaaan** [comment]
Some of the values are found in the config file for numismatic-overhaul.
You can find this file named `numismatic-overhaul.json5`, in your `.minecraft/config` folder.

**Comment by wsxiya** [comment]
> 一些值可以在钱币大修的配置文件中找到。您可以在您的文件夹中找到名为 的文件。`numismatic-overhaul.json5``.minecraft/config`

I used "Sinytra Connector" to load Numismatic Overhaul on forge, but I also added Alex's Mobs. I found that the currency used by Alex's Mobs villagers for transactions is still Emerald. How should I replace Emerald with Silver Coin or Bronze Coin?
