### ISSUE TITLE
[1.19.2 - Fabric Server] Crash on startup

### ISSUE THREAD

**Issue by loveavulsion** [glisco03/numismatic-overhaul#115]
Crash log: https://pastebin.com/Qmk9CLEs

I'm running a server, and I was having this particular crash. I couldn't find any info on this error online, except in one particular case which was dismissed because of a cracked client. I am not running a cracked client.

I did a [binary search method](https://www.reddit.com/r/feedthebeast/comments/evpy6r/tips_for_modpack_authors_how_to_find_misbehaving/) on my mods, and I have isolated the issue to this mod in particular.

I'm sorry I can't provide more information, as there is nothing particularly human-readable about the crash, and I am not a programmer in Java. The server _only_ crashes with Numismatic Overhaul installed, but I have no idea why.

This mod is really good! I'm impressed with the work and it's exactly what I'm looking for.
Thank you for reading, and of course feel free to request additional information.

**Comment by Noaaan** [comment]
This issue should be fixed as of the latest release of Numismatic Overhaul. We backported a fix for this particular issue, as Fabric Loader 0.15.0+ fixed a bug which affected a lot of mods.

**Comment by loveavulsion** [comment]
~~Could you please tell me the version code of that version so that I can double check that the Modrinth page is up to date with the latest release?~~

Assuming version 0.2.10 as listed on the GitHub repository is the latest version, I can confirm that Modrinth is up to date. Did you release an update since I opened this issue?

**Comment by Noaaan** [comment]
Yes. 0.2.11 is the latest version.

**Comment by Infinixius** [comment]
I have the exact same problem as OP, but I'm confused as to the fix. [[1.19+] Numismatic Overhaul - 0.2.10](https://modrinth.com/mod/numismatic-overhaul/version/0.2.10+1.19) (the latest release on GitHub and Modrinith) still gives me the same error with Minecraft 1.19.2 and Fabric 0.15.1.

Here is the crash log, if it helps. [https://pastebin.com/Nxzwib5G](https://pastebin.com/Nxzwib5G)
