### ISSUE TITLE
[Urgent] Duplicate any item easily with shop block

### ISSUE THREAD

**Issue by UnnamedWei** [glisco03/numismatic-overhaul#116]
Step 1:Owner puts something in the shop
Step 2:Another player opens the shop screen but dont close it
Step3:The Owner takes item out
Step4:Another player buys it and there you have two of that item now

This happened on my server and I have to temporarily ban all player shops, waiting for a fix, thank you very much

**Comment by UnnamedWei** [comment]
Version：Fabric 1.20.1

**Comment by UnnamedWei** [comment]
Suggestion:
1. Could you make it that when someone is trading the owner can’t open it or destroy it something to fix this?
2. Can you make the creative mode shop (infinite shop block) indestructible (make it like bedrock)?
3. Thanks a lot

**Comment by Noaaan** [comment]
For feature suggestions please open new issues, as tracking them inside an important bug report like this is not ideal.
As for your two suggestions: the first has been implemented as part of the fix as of 0e62c8a6b8b8507362dd605bdba055ce04d8c5a7. It is scheduled for the next release.
The second suggestion is not something we are interested in implementing. Frankly, having shop blocks act as Bedrock, *a completely unbreakable block*, will lead to abuse where it is treated as such. Claim mods and protection mods already solve this issue.

**Comment by UnnamedWei** [comment]
Will the new release with the fix possibly clear or disable previous trades in the shop block that already exist in a server/world? Thanks

**Comment by Noaaan** [comment]
Not sure exactly what you mean by this. Do you mean removing the inventories of shop blocks? No. This is not something we would do, as it doesn't make a ton of sense, as well as leading to confusion among why items suddenly disappeared from shops.
There is nothing wrong with the trades themselves, but the logic of performing the trade, which has now been fixed.

**Comment by UnnamedWei** [comment]
When will the next update be? Will there be new content added beside this fix? We really love this mod and are looking forward to it. Thanks. ☺️

**Comment by Noaaan** [comment]
Unfortunately it is a bit hard to say when exactly we have the possibility to make a release, due to being in the middle of the holiday season. Generally it will be released as soon as possible

**Comment by Noaaan** [comment]
Fixed as of 0.2.12 for 1.20.1 and 1.20.2. Thanks for reporting!
