### ISSUE TITLE
[suggestion/feature] Moving the purse icon via keybind

### ISSUE THREAD

**Issue by Xplodin** [glisco03/numismatic-overhaul#120]
I love the mod, but cant quite move the purse icon without having to reboot my game.
Not much documents the config.
Maybe middle mouse click and drag can move the icon to where we want?
Just a suggestion. Would love to see it :)

**Comment by Noaaan** [comment]
You can very much change the config in-game by opening the config screen. This can be done via Mod Menu, or with the `/owo-config` command.
Opening the screen also allows you to reload the config from file by pressing the reload button

**Comment by Xplodin** [comment]
My b, I didnt know about the owo-config command. Thank you for the explanation!
