### ISSUE TITLE
[Suggestion] Disabling coin drops from illagers

### ISSUE THREAD

**Issue by Vampzula** [glisco03/numismatic-overhaul#122]
I would like to suggest adding a function to the config that will allow you to disable the drop of coins from illagers. This feature will be useful on some servers and will not allow you to farm currency from Outposts.

This might be useful to someone

Tnx google!

**Comment by UnnamedWei** [comment]
Hello
I think this can be solved easily by editing your mod file, you can find a file called the bourgeoisie and then remove the illager label in it.
Hope this will be helpful

**Comment by BasiqueEvangelist** [comment]
Editing the `.jar` to edit the `numismatic-overhaul:the_bourgeoisie` tag really isn't a good idea, as you'll have to do it again every update and you won't be able to easily put this in modpacks.

A better approach is to [make a datapack](https://github.com/wisp-forest/alloy-forgery/wiki/Datapack-Tutorial) and add a
tag JSON under `data/numismatic-overhaul/tags/entity_types/the_bourgeoisie.json`, there's an example of such a datapack in the #numismatic-overhaul channel in the Discord.

**Comment by gliscowo** [comment]
Given that this is already possible using the solution provided in the comment above, I'll go ahead and close this as not planned

Cheers
