### ISSUE TITLE
[Suggestion] Add a wealth ranking

### ISSUE THREAD

**Issue by UnnamedWei** [glisco03/numismatic-overhaul#124]
List the rank of all player’s wealth or just non-op players

**Comment by gliscowo** [comment]
While this is certainly a neat feature for more economy-esque mods like the many plugins of the Bukkit/Spigot ecosystem, it's not something we see as a good addition for Numismatic Overhaul. It is, after all, a gameplay-focused mod and the physical coins are part of the primary selling point - and hey, if you need to flex your wealth it is certainly much more impressive to have an inventory full of coins than to see some meaningless number on a list generated by a magic command

As such, I'll be closing this as not planned
Cheers
