### ISSUE TITLE
New villager for buying emeralds

### ISSUE THREAD

**Issue by Polarite** [glisco03/numismatic-overhaul#13]
I cant get emeralds from villager trading anymore so it would be nice to have a villager thats made by placing shop as a work station and sells/buys emerald iron gold diamond and or so

**Comment by gliscowo** [comment]
Hey, hope you're doing good. Just to give an explanation on our standing, Emeralds are supposed to be pretty rare within Numismatic. Raising their value is in fact on the design goals of the mod - as such we will not be adding a Villager which sells them. You are however perfectly welcome to add some trades yourself , with a datapack - customizability is another design goal after all
Cheers

**Comment by Polarite** [comment]
my issue was about dank storage requiring 8 emerald blocks for next dank, would be great if you could add a way for buying emeralds
