### ISSUE TITLE
[Bug/Urgent] Duplicate any items with teleportation while opening the shop

### ISSUE THREAD

**Issue by UnnamedWei** [glisco03/numismatic-overhaul#130]
Steps:
1. Open the shop
2. Use end pearl or teleport by another player to leave the current chunk but the shop screen stays open
3. Buy something
4. The shop in the origin chunk won’t have items removed because the chunk is unloaded

This happened on my server and we have to shut down the server temporarily to prevent more duplicates, it’s really urgent, could you please fix this?

**Comment by Noaaan** [comment]
What version of Numismatic Overhaul were you using at the time?

**Comment by UnnamedWei** [comment]
0.2.12 the newest one for fabric 1.20.1

**Comment by UnnamedWei** [comment]
Can this be solved? Maybe force the shop screen to close after player leaves or the process can only be done if the player is loading that shop block?
