### ISSUE TITLE
[Bug/Duplication] When someone break the shop block and another one opens it the money duplicates 

### ISSUE THREAD

**Issue by UnnamedWei** [glisco03/numismatic-overhaul#133]
1. The owner opens the shop block
2. Another person breaks it and get the money
3. The owner’s shop screen stays so he can withdraw the money again

**Comment by gliscowo** [comment]
Fixed in [0.2.14](https://modrinth.com/mod/numismatic-overhaul/version/0.2.14+1.20.2). For some reason I feel like this won't be the last time 😂 

Cheers
