### ISSUE TITLE
Requesting Compatibility with Trinkets/Switchy [FABRIC 1.20.4] 

### ISSUE THREAD

**Issue by Dumpling00** [glisco03/numismatic-overhaul#136]
Switchy is a mod that allows you to have different character presets in your single player world, it comes with add-ons to make it so each preset can also have their own inventory, healthbar, exp and trinkets. (Without these add-ons, inventories etc are shared across characters, which is what happens with the purse.)

It would be amazing to make it so each character preset could have their own purse and money, which I believe could be solved by just allowing the player to put the purse in a trinket slot, not too different from how Travellers Backpacks does it.

I've tried approaching the Switchy devs about this but I haven't received a response.

Hoping for your consideration, I thank you for your time and dedication.

**Comment by Noaaan** [comment]
Solved as of https://github.com/wisp-forest/numismatic-overhaul/commit/3fe23064089e418e4d058a2eae478b97e9af161c
