### ISSUE TITLE
Fletcher villagers' tipped arrows are of type "uncraftable" and have no effects

### ISSUE THREAD

**Issue by OfficialLahusa** [glisco03/numismatic-overhaul#16]
Steps to reproduce:

1. Level fletcher villagers until any tipped arrow trade is visible
2. Hover over the offered item to inspect it

![grafik](https://user-images.githubusercontent.com/34841946/159165337-29e23dac-babf-425c-bc19-613902d99376.png)

**Comment by OfficialLahusa** [comment]
Sidenote: The stacks of unstackable items are kind of unnatural too

**Comment by Noaaan** [comment]
Looking back at it the fletcher trades are almost as old as this repo. They definitely need some more love.

I will be digging through the trades the coming week to weed out and fix these old placeholders with better trades. Thanks for pointing them out!

**Comment by gliscowo** [comment]
This and a multitude of other problems should now be resolved in [0.2.0](https://modrinth.com/mod/numismatic-overhaul/version/0.2.0+1.18). Should you find any more, definitely open another issue
Cheers
