### ISSUE TITLE
Hopper and tubes support

### ISSUE THREAD

**Issue by Niketats** [glisco03/numismatic-overhaul#17]
What about to make possible items to be load/unload in shops via hopper and tubes?

**Comment by gliscowo** [comment]
Technically I would be open to this, but how would you effectively prevent theft if automated access to the shops inventory is possible

**Comment by Niketats** [comment]
I think this is players' concern how to protect their shops, but maybe you can make it turnable for every player's specific shop, this option can be useful for servers with claiming mods like Flan or FTB Chunks, where shop can be protected via claim

**Comment by gliscowo** [comment]
The latest release, [0.2.0](https://modrinth.com/mod/numismatic-overhaul/version/0.2.0+1.18) now allows you to insert items into your shop, with a toggleable option. We will probably never add extraction, as there isn't really much sense in it cause it could only be used to steal items that should be sold
Cheers
