### ISSUE TITLE
I would like to request that you add OctoEconomyApi support....

### ISSUE THREAD

**Issue by JadianRadiator** [glisco03/numismatic-overhaul#18]
I would like to request that you add [OctoEconomyApi](https://github.com/ExcessiveAmountsOfZombies/OctoEconomyApi) support so that I don't have to manually modify the [Professions](https://www.curseforge.com/minecraft/mc-mods/professions-fabric) mod's datapack to reward Numismatic's currency.

**Comment by gliscowo** [comment]
Given that it is apparently possible to achieve this via a datapack and implementing this API is no simple task, we don't currently plan on doing this. Should the API establish itself as a standard at some point in the future, we might consider it again but for now this is a clear no from us
Have a nice day

**Comment by JadianRadiator** [comment]
The datapacks as they are now can only do mismatic coins as items dropped
on the ground,
and not as raw currency.
Doing this integration would allow having OctoEconomyApi handle the
conversion for me.
The datapacks requires me to manually decide how much coin to internal
money.

**Comment by gliscowo** [comment]
What you're asking us here is to implement an entire API just to save you some work balancing your datapack - something which I do not see as reasonable at all. Maybe I wasn't clear enough when I stated this earlier - this isn't just a simple case of adding compat. For a clean solution we would need to write an implementation for the whole API - something which is neither simple nor quick
