### ISSUE TITLE
Mineraft crashes with only your mod installed

### ISSUE THREAD

**Issue by Brimstine** [glisco03/numismatic-overhaul#2]
[latest.log](https://github.com/gliscowo/numismatic-overhaul/files/7890343/latest.log)

**Comment by Noaaan** [comment]
The crash is due to the full Cardinal Components API package breaking the game, not directly from Numismatic Overhaul. 
We are working on a fix to only include the required modules so you don't have to download them.

**Comment by gliscowo** [comment]
Fixed in 0.1.5
