### ISSUE TITLE
Incompability with The One Probe Fabric

### ISSUE THREAD

**Issue by sirben99** [glisco03/numismatic-overhaul#21]
Hey!

I was sorting through my modpack to see what mod causes The One Probe to disconnect me from singleplayer world (Not crash, disconnect) when looking at a block.

Log:
https://pastebin.com/HF4SggVQ

If this is something i have to report on The One Probe issue tracker and its on theyr end, please let me know and sorry for wasting ur time here!

Ben

**Comment by gliscowo** [comment]
First of all, thanks for reporting! After some investigation we discovered that this isn't directly a problem related to Numismatic but rather to Stacc, on of its dependencies. I've talked to the maintainer of TOP Fabric and a fix should be out soon. I'll keep this issue open until it's fixed on his end
Cheers
