### ISSUE TITLE
adds empty tag to items

### ISSUE THREAD

**Issue by immortal-cabbage** [glisco03/numismatic-overhaul#24]
I have found that when i move coins to my inventory, if there are other items present, they will receive and empty tag. 

For example: 

if i have 1 iron ingot in my inventory and some bronze coins, i will shift click the pouch to move the coins. they will move as expected, but when i try to stack another iron ingot onto the one in my inventory it will not stack. if i check in nbt editor or use the 'data get entity @p' command, the iron ingot in my inventory during the coin move will have tag: {} appended to it. i will test to see if this happens with no other mods installed, but wanted to make a notice as i finally found the issue. thanks for the great mod btw,

**Comment by gliscowo** [comment]
What version of the mod are you on? This should be fixed in 0.2.0 🤔
Cheers

**Comment by immortal-cabbage** [comment]
yeah i am actually just in the process of testing the new version, sorry. i will update here after i check it.

**Comment by immortal-cabbage** [comment]
it is fixed as far as i can tell. thanks for the fix and the quick response. sorry to bother you!
Cheers
