### ISSUE TITLE
Incompatibility with Quilt on 1.19.

### ISSUE THREAD

**Issue by paulhlschr** [glisco03/numismatic-overhaul#26]
### Reproducible?
✅ Yes.

### Minecraft Version
`1.19`

### Mod Loader Version
Quilt Loader `0.17.1-beta.1`

### Mod Versions
| Mod Name | Mod Version |
| ------------ | -------------- |
| QSL + QFAPI | 2.0.0-alpha.2+0.55.3-1.19 |
| owo-lib | 0.7.3+1.19 |
| Cloth Config | 7.0.72 |
| Numismatic Overhaul | 0.2.2+1.19 |

### Log Files
[latest.log](https://github.com/wisp-forest/numismatic-overhaul/files/8886051/latest.log)
[crash-2022-06-12_16.36.02-client.txt](https://github.com/wisp-forest/numismatic-overhaul/files/8886052/crash-2022-06-12_16.36.02-client.txt)

### Reproducible?
❌ No.

### Minecraft Version
1.19

### Mod Loader Version
Fabric Loader `0.14.7`

### Mod Versions
| Mod Name | Mod Version |
| ------------ | -------------- |
| Fabric API | 0.55.3-1.19 |
| owo-lib | 0.7.3+1.19 |
| Cloth Config | 7.0.72 |
| Numismatic Overhaul | 0.2.2+1.19 |

### Log File
[latest.log](https://github.com/wisp-forest/numismatic-overhaul/files/8886062/latest.log)

**Comment by BasiqueEvangelist** [comment]
Could you test this again with the newest alpha version of QFAPI? It should fix this issue.

**Comment by paulhlschr** [comment]
It is fixed by the new QFAPI version. Thank you very much for reporting it to them!
