### ISSUE TITLE
[Request / Question] Exchange emeralds for coins?

### ISSUE THREAD

**Issue by ConqAra** [glisco03/numismatic-overhaul#27]
I don't know what good are emeralds for anymore, is there a use to them at this point? It'd be nice if they could be exchanged into coins such as silver or gold.

It's mainly to get my question solved though if this isn't planned to be a feature for the mod; What use do emeralds have now that I have this mod? It's very nice but I am wondering if emeralds are even useful- currency-wise- I don't mean in regards to depending on other mods using them for a recipe.

**Comment by gliscowo** [comment]
There are some trades spread over a few of the villagers which already more or less let you do this. In general we do not plan on adding any sort of direct exchange mechanism - after all the entire point of Numismatic is to move away from Emeralds as a currency. So to answer you question: No, Emeralds do not serve much of any purpose currency-wise
Cheers
