### ISSUE TITLE
[1.18.2/1.19] Small GUI Issue with Inventorio (Moveable GUI?)

### ISSUE THREAD

**Issue by ConqAra** [glisco03/numismatic-overhaul#28]
Bit of an issue with inventorio for the money bag GUI when flicking to the normal inventory

Maybe an option to move where the bag GUI is so we can fix unnecessary problems such as this with inventorio when you switch to the normal gui.

GUI normally with inventorio
![image](https://user-images.githubusercontent.com/76233356/175765472-726e1fe3-571e-4629-a7ec-eedec99209f1.png)

GUI issue when you flick it to normal (needed when using trinkets with inventorio)
![image](https://user-images.githubusercontent.com/76233356/175765428-8c65411b-43e6-4160-9a87-720f88501589.png)

**Comment by gliscowo** [comment]
This is now implemented in [0.2.3](https://modrinth.com/mod/numismatic-overhaul/version/GZccdAdg) for 1.19. You can now completely control the position of the purse widget with two new config values
Cheers
