### ISSUE TITLE
[Requiem] Disassociating from a body makes you lose more coins

### ISSUE THREAD

**Issue by DarianLStephens** [glisco03/numismatic-overhaul#29]
If you voluntarily leave a body without dying, you will drop more coins again, which makes this aspect of Requiem a problem.

**Comment by gliscowo** [comment]
Given that we drop your coins in the same method which makes items with Curse of Vanishing disappear this is at best weird behavior and at worst a bug in Requiem. While this may be something we can fix on our side, we don't deem it worth the effort given that you can already mitigate it by simply setting the `moneyDropPercentage` gamerule to `0`
Cheers
