### ISSUE TITLE
`java.lang.ArithmeticException: / by zero` when adding coins from mod to vanilla bundle

### ISSUE THREAD

**Issue by James103** [glisco03/numismatic-overhaul#3]
When adding any type of Coin to a vanilla Bundle (which can be obtained from Wandering Traders with this mod installed), the game crashes with `java.lang.ArithmeticException: / by zero` because the stack size of the coin (99) exceeds the vanilla stack size (64), and therefore 1 coin takes up less than one bundle slot. The only nonnegative integer less than one is zero, but anything divided by zero is undefined, hence the exception.

To reproduce:
1. Obtain some coins
2. Obtain a Bundle from a Wandering Trader as shown below.
3. Attempt to put any amount of any coin inside the bundle.
4. Game crashes
5. Restart game and rejoin world
6. Coins are dropped.

![image](https://user-images.githubusercontent.com/37945304/150435912-5922fa10-17c9-4eb9-a29b-e33f30f878f9.png)

**Comment by gliscowo** [comment]
First of all, thank you for reporting. This is a severe problem we didn't foresee, and that I can't think of a good solution for either. I would assume for the time being the best course of action is to simply not allow coins in a bundle, given that money bags already serve that purpose. If you have any better ideas though, please tell us
Cheers

**Comment by gliscowo** [comment]
Fixed in 0.1.5
