### ISSUE TITLE
[Suggestion] Add an option to disable Pillager drops and other loot tables

### ISSUE THREAD

**Issue by ghost** [glisco03/numismatic-overhaul#30]
This would make it possible to use the currency better in some server scenarios where no currency aside from server trading should be added.

**Comment by Noaaan** [comment]
We might look into making a config option for disabling the loot tables through config.
As for mob drops, you can override it with a datapack by creating an empty `numismatic-overhaul:the_bourgeoisie` tag, setting replace to true

**Comment by ghost** [comment]
Thanks! Maybe remove the pillager within the code and add it as a datapack for ease of use then? I feel like not everyone (myself included) knows how to make a datapack that overwrites something from scratch, while editing a file that's structure is already there is much easier to understand.

**Comment by Rushmore75** [comment]
A config would be easier, agreed

**Comment by gliscowo** [comment]
I've now partially implemented this suggestion in e2813b2, which allows you to disable chest loot generation. Since the bourgeoisie are part of the mod's static data however, we can't currently provide a config option to disable them - a datapack will stay the only option for the time being
Cheers
