### ISSUE TITLE
[Suggestion] Add a shop for buying items

### ISSUE THREAD

**Issue by ghost** [glisco03/numismatic-overhaul#31]
If I understand the current shop right, it can only be used to sell items. A shop to buy items would add up nicely!

**Comment by gliscowo** [comment]
When originally designing Numismatic we specifically decided against the ability to buy items, for a variety of reasons. Primarily we failed to see much practical use. Say you're putting up a Shop which buys some item you need - how will people get aware of that? It would practically require them to constantly go around checking everyone's shops for what they're currently buying - you're much better off simply asking in chat and doing a direct exchange. That being said, we're open to discussion and if you can make a good argument for why and how this makes sense in actual gameplay please tell us and we might change out stance
Cheers

**Comment by ghost** [comment]
My original idea was to add it so that people can sell to the server. But then I realized that the same can be achieved with a custom villager trade. 

Maybe my fingers were faster than my brain here... 

But thanks for taking the time! 🤍

**Comment by gliscowo** [comment]
As we seem to agree here, I'll close this issue now - feel free to reopen it if you have more to say
Have a nice day
