### ISSUE TITLE
shop protection

### ISSUE THREAD

**Issue by Dr-WeiAL** [glisco03/numismatic-overhaul#33]
Other players on the server can destroy someone else's shop
Version 1.18.2
mod version 0.2.2

**Comment by gliscowo** [comment]
Because allowing people the create infinite unbreakable blocks is just a bad idea in many different ways, this will not be implemented natively in Numismatic. If you need to have protected shops, I recommend you install one of the many claim/protection mods like FTB Chunks or Get Off My Lawn
Cheers
