### ISSUE TITLE
Fabric 1.19 add chance drop money with mobs and monsters.

### ISSUE THREAD

**Issue by MrJorman** [glisco03/numismatic-overhaul#35]
Please add chance drop and amount money from mobs and monsters!

**Comment by gliscowo** [comment]
You can already accomplish this. All you need to do is adding the entities which you want to drop money to the `numismatic-overhaul:the_bourgeoisie` entity type tag. If you need help on doing that, check out [this datapack tutorial](https://github.com/LordDeatHunter/Alloy-Forgery/wiki/Datapack-Tutorial)
Cheers

**Comment by MrJorman** [comment]
chance??
