### ISSUE TITLE
Feature: Use gold coins to barter with Piglins

### ISSUE THREAD

**Issue by James103** [glisco03/numismatic-overhaul#4]
Currently, villagers trade using coins, but piglins do not. Piglins still barter with gold ingots, even though gold coins may seem like a good alternative.

Either:
* Piglins barter with only gold ingots, which is vanilla behavior.
* Piglins barter with either gold ingots or gold coins.
* Piglins barter with gold coins **only**.

That last option will mean players will have to trade a lot or kill thousands of pillagers to acquire the necessary wealth for a good bartering session. For example, a single Soul Speed III book will cost upwards of 300 gold coins (or more) to obtain.

**Comment by gliscowo** [comment]
This will most likely be added at any point in the near future, as reworking Piglins like that would be a balancing nightmare which we don't want to take on for now. The situation isn't as simple as just replacing Gold Ingots with Gold Coins as their values are drastically different and bartering would most likely become severely underused in most situations. While I do see that this might be nice to have at some point in the distant future, for now I'll close this and hope you can understand my reasoning
Cheers
