### ISSUE TITLE
It crashes as soon as I select it (coin) in the inventory

### ISSUE THREAD

**Issue by hanloon** [glisco03/numismatic-overhaul#40]
game version:1.19.1
Fabric version:0.14.9
Mod version:0.2.3
log:-1

**Comment by Noaaan** [comment]
Please provide a crash report and your game log of when this crash occured. Otherwise we cant tell what is crashing

**Comment by hanloon** [comment]
The game crashes without any reports but shows -1

**Comment by Noaaan** [comment]
This is why I asked for your game log, or rather your `latest.log`. It contains a lot more useful information than a non-existing crash report. 
See this for more information: https://fabricmc.net/wiki/player:tutorials:logs_ml:windows

**Comment by hanloon** [comment]
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Unknown TooltipComponent
結束代碼：-1

**Comment by hanloon** [comment]
end code: -1

**Comment by Noaaan** [comment]
There is no way for me to reproduce this without the log. Please post it, or I am unable to help you

**Comment by gliscowo** [comment]
As this issue has now been stale for over a month, I'll go ahead and close it. If you can actually provide the log to us, please re-open it so we can figure out what's going on
Cheers
