### ISSUE TITLE
[request] Add a config option for pillager coin drops

### ISSUE THREAD

**Issue by Maetick** [glisco03/numismatic-overhaul#42]
I would love to use this mod for a money system in my SMP server. But the fact that pillagers drop coins means that one pillager raid farm could crash the server's economy. I love that there is a config option to turn off villager trades but if you could also add one for pillager drops that would be awesome.

**Comment by gliscowo** [comment]
Which mobs drop coins is determined by an entity type tag, specifically `numismatic-overhaul:the_bourgeoisie`. To completely disable drops, simply create a datapack which has this tag be empty with `replace` on `true`
Cheers

**Comment by Maetick** [comment]
I folIowed a few tutorials on YouTube. And made several attempts at making a datapack and non of them worked. I don't know if I had the file structure wrong or the code in the tag json file wrong. I'm attaching my most recent attempt. Would it be too much to ask that you make the datapack for me?
[coins.zip](https://github.com/wisp-forest/numismatic-overhaul/files/9293503/coins.zip)
.

**Comment by BasiqueEvangelist** [comment]
> I folIowed a few tutorials on YouTube. And made several attempts at making a datapack and non of them worked. I don't know if I had the file structure wrong or the code in the tag json file wrong. I'm attaching my most recent attempt. Would it be too much to ask that you make the datapack for me? [coins.zip](https://github.com/wisp-forest/numismatic-overhaul/files/9293503/coins.zip) .

You specified the `minecraft:entity_type_tag` tag, not the `numismatic-overhaul:the_bourgeoisie`. You should move the tag file to `data/numismatic-overhaul/tags/entity_types/the_bourgeoisie.json`.
Also, your tag file is wrong, as you're trying to replace the tag with one containing a pillager and a "the_bourgeoisie". It should be this if you want to replace it with an empty tag:
```json
{
  "replace": true,
  "values": []
}
```

**Comment by Maetick** [comment]
Thank you. It's working now.
