### ISSUE TITLE
Purse window in inventory GUI is clickthrough

### ISSUE THREAD

**Issue by Timolino456** [glisco03/numismatic-overhaul#46]
When for example having the inventory buttons from the mod Inventory Profiles Next enabled and opening the purse in the inventory, it is possible to click on the inventory buttons through the purse window. It is also possible to click on the crafting result box behind the gold coin. I guess you didn't make the purse window non-clickthrough.
This is a rather minor issue, but I already misclicked the "sort inventory button" twice because of it lol. I don't really see any benefit of having it clickthrough either, so I think it should be changed, if possible.

In the image I had my cursor on the arrow up button of the gold coin, as you can see the crafting result box also gets "selected" (edited to show a version that has the buttons from Inventory Profiles next enabled, as in the first screenshot they were disabled for testing)

Thank you for this cool mod!
![image](https://user-images.githubusercontent.com/38137599/190249533-e7ed38ea-8f9e-4060-bbc6-9e20d0882157.png)

**Comment by Noaaan** [comment]
If you are on the latest version of Numismatic you should be able to move the purse icon through its config. You can access it through Mod Menu or through the config folder.

**Comment by gliscowo** [comment]
The purse does in fact not allow clicking the widgets below it. From what I can tell, IPN simply grabs the mouse input before it ever even reaches the screen - apart from building some very nasty specific compatibility there's nothing we can do about this. This might stay a small compatibility problem indefinitely - for the time being I myself will definitely not fix it
Cheer
