### ISSUE TITLE
`numismatic balance get` and `numismatic balance set` require permission level 4 instead of 2

### ISSUE THREAD

**Issue by James103** [glisco03/numismatic-overhaul#5]
I was thinking of constantly updating scoreboard values based on a player's Numismatic balance and possibly vice versa. These scoreboard values can be used for e.g. server-wide leaderboards, custom advancements, and more.

For example, the following commands are effectively the same and should require the same permission level, yet the second is more performant:
1. `data get entity @s cardinal_components.numismatic-overhaul:currency.Value`
2. `numismatic balance @s get`

Therefore, the minimum required permission level for `numismatic balance get` (and ideally `set` as well) should be lowered to 2 instead of the current 4. This can be done by changing the 4 to a 2 in the following line:
https://github.com/gliscowo/numismatic-overhaul/blob/866f30c3ab83e190c71c9039e824c07eb8c3dd43/src/main/java/com/glisco/numismaticoverhaul/NumismaticCommand.java#L23

---
Permission levels, as summarized from the [Minecraft Wiki](https://minecraft.fandom.com/wiki/Permission_level):
* 1 -- Bypass spawn protection
* 2 -- Use commands that affect the world. Examples: `/data`, `/xp`, `/scoreboard`, `/give`
* 3 -- Use commands that are meant for multiplayer management. Examples: `/ban`, `/kick`, `/op`
* 4 -- Use commands that are meant for server management. Examples: `/stop`, `/reload`, `/datapack`, `/save`

**Comment by gliscowo** [comment]
Added in 0.1.6, when it gets released in a few minutes
