### ISSUE TITLE
Game crashes upon trading - Resolved

### ISSUE THREAD

**Issue by Foxren** [glisco03/numismatic-overhaul#50]
Game crashes everytime trading with a villager for a trade, which would give the player more money than they have free inventory slots
Game version: 1.19.2
Mod version: 0.2.3

**Comment by Noaaan** [comment]
Now I really have to ask what the crash actually was

**Comment by Foxren** [comment]
Hello, sorry for opening an issue just to find out it wasn't caused by this mod. I've quickly found out that it was caused by a mod adding animations to items switching slots in the inventory. From which it seems like multiple animations/items switching at the same time (for example buying several stacks of items at once) caused the game to crash
