### ISSUE TITLE
[2 BUGS] Villiager Shop and own Shop

### ISSUE THREAD

**Issue by f0kx** [glisco03/numismatic-overhaul#51]
![Bild_2022-11-11_024205249](https://user-images.githubusercontent.com/14795020/201243731-545b7e69-f4cc-4e5e-8306-838bb525747a.png)
1. Its nor possible to have more than 64 when shop wants 96 its not possible to buy some!
2. its not possible to have a shop with items because they vanish when they will put in the slot where the money will set!
Version: last: 1.19
minecraft : 1.19
Forge 43.1.43

**Comment by f0kx** [comment]
https://user-images.githubusercontent.com/14795020/201245319-18ab6ec5-49d1-4e8e-bf8e-ece21578d57e.mp4

**Comment by Noaaan** [comment]
We do not maintain a Forge version of Numismatic Overhaul. Please report these issues to the correct trackers.
