### ISSUE TITLE
[Console Entry] Shift Right Click on both Shops / Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [glisco03/numismatic-overhaul#57]
1. Shift Right Click on Inexhaustible Shop
2. Shift Right Click on Normal Shop

Client [latest.log](https://gist.github.com/SpigotDE/dc52543407956229fd8231000e8754c9)

**Comment by Noaaan** [comment]
This issue is caused by Numismatic Claims. I suggest opening an issue on their repo informing them of this crash

**Comment by xR4YM0ND** [comment]
Fixed in Numismatic Claims 1.0.2
