### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by LRDGNMS** [glisco03/numismatic-overhaul#59]
Hi, Ive changed some things like villiger trades because they were broken as fuck, how can i export it into mod ?

**Comment by Noaaan** [comment]
If you want to start modding, there are many tutorials out there, for example on YouTube, which are useful to get started. The Fabric wiki is also a good resource: https://fabricmc.net/wiki/tutorial:primer

In your case you might want to distribute a Datapack instead, as all the trades would be overwritten by the ones you have made. Again, there are many resources for this, I can recommend PlanetMinecrafts tutorial: https://www.planetminecraft.com/forums/minecraft/datapacks/function-data-packs-for-dummies-a-tutorial-blog-series-604217/

Do note that this issue tracker is meant for, well, issues about Numismatic Overhaul, and not for general modding advice.
