### ISSUE TITLE
Players are unable to complete trades when the price being charged is over 99 gold coins, causing coin losses

### ISSUE THREAD

**Issue by James103** [glisco03/numismatic-overhaul#6]
As of mod version 0.1.15 for Minecraft 1.18.1, when a player attempts to make a trade that would cost more than 99 gold coins, instead of being able to complete the trade if the player has enough money, the following will occur:
* 99 gold coins will be withdrawn from the purse.
* (X - 99) gold coins will be voided.
* The player will be unable to complete the trade as only 99 out of X gold coins have been paid.

Attempting to try again will lead to the same result and another (X - 99) gold coins coins being deducted from your purse.
Where: X is the true price of the trade (in gold coins).

Trades with such high prices can be reproduced in two ways:
1. Summon a villager, get it really angry at you, then try to trade with the villager.
2. Craft and place a shop, configure it to sell an item (such as Soul Speed III) for 300 gold coins (or something more reasonable like dirt for 1s 1c), then have another wealthy player (or the owner if shift-clicking) with at least that many coins open the shop and try to execute the trade. (This will work, and the player is able to complete the trade, but clicking on the trade again voids coins)

This basically would need to be solved with the following:
* Allow villagers to use money bags for trading large amounts of coins or multiple denominations, or cap prices at 99 gold coins.
* Prevent coins from being voided when clicking the same trade multiple times where possible.

**Comment by gliscowo** [comment]
Have you verified that this only happens in 0.1.5? I don't think I have touched any code related to this. If this is actually the case however, the fix should trivial

**Comment by James103** [comment]
I have verified, all in 0.1.4,
* Shop items with prices that are money bags void coins when players click on the same trade twice.
* Villagers whose trade price exceeds 99 gold coins do not let players complete their trades (stack size limitations).
