### ISSUE TITLE
Can't join server when using Numismatic overhaul

### ISSUE THREAD

**Issue by CordedPepper72** [glisco03/numismatic-overhaul#60]
I tried a modpack with this mod in it and it does not let me join servers. I confirmed this was the right mod as when I removed it from my mods folder I could join. this is the error message I get when trying to join a server "Internal Exception: io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.IOException: Root tag must be a named compound tag"
[latest.log](https://github.com/wisp-forest/numismatic-overhaul/files/10105773/latest.log)

**Comment by gliscowo** [comment]
From the log you sent it looks like this error is occurring primarily on the server. Could you get us the server log from a time this happened?

**Comment by CordedPepper72** [comment]
This isn't my server but it was a server people were playing on at the time so it's not the server
This is another log of me opening Minecraft any trying to join the server. Also from what ive seen on google it shows I logged on and logged off to the server but I don't have an alt so I can't check:
[latest.log](https://github.com/wisp-forest/numismatic-overhaul/files/10115112/latest.log)

**Comment by CordedPepper72** [comment]
Also I know it is the mod as when I take just the mod off I can join servers just fine

**Comment by Noaaan** [comment]
To me this seems like an owo-networking error, as you are immediately being kicked due to some packet issue.
Numismatic Overhaul is not a serverside or clientside-only mod, and needs to be present on both the client and server you are connecting to.

**Comment by CordedPepper72** [comment]
OMG im so stupid I thought it was clientside and so tried to conntect to a modded minehut server but you need to go through a lobby without the mod to do that. the only problem was it was both serverside and client side
