### ISSUE TITLE
Client crashes when oppening shop (not charm incompatibility)

### ISSUE THREAD

**Issue by Allomere** [glisco03/numismatic-overhaul#63]
[crash-2022-12-15_03.44.36-client.txt](https://github.com/wisp-forest/numismatic-overhaul/files/10234477/crash-2022-12-15_03.44.36-client.txt)
I dont have charm installed on my server, but when players try to open a shop it crashes their client

**Comment by Noaaan** [comment]
Duplicate of #62 
We have already fixed it, and it is planned for next release

**Comment by gliscowo** [comment]
Fixed in [0.2.6](https://modrinth.com/mod/numismatic-overhaul/version/RH84wQRG)
