### ISSUE TITLE
Purse resets when opening recipe book

### ISSUE THREAD

**Issue by ghost** [glisco03/numismatic-overhaul#74]
Minecraft: **1.19.2**
Fabric loader: **0.14.14**
Fabric API: **0.73.2**
OwO Lib: **0.9.3**
Numismatic Overhaul: **0.2.8**

https://user-images.githubusercontent.com/108554062/217428862-7d67484e-2365-42c9-9178-1978e940fee3.mp4

When using a custom position for the purse widget, it reverts back to its original position when opening the recipe book (and stays there until the inventory is completely closed and reopened.) Tested in a fresh instance with only the mods listed above.

**Comment by gliscowo** [comment]
Thanks for reporting this problem, it has now been fixed in [0.2.9](https://modrinth.com/mod/numismatic-overhaul/version/W8o5cKwW)
