### ISSUE TITLE
Some mad crazy suggestions

### ISSUE THREAD

**Issue by ChromaPIE** [glisco03/numismatic-overhaul#75]
I decided to post it cuz this is the most singleplayer-friendly currency mod ever, at least for now, so it might be even more amazing to make it take one step further.

When you have Hero of the Village on you (or ever had this effect on you since having to fighting back raids again and again would be kinda lame), you can ask for a _magical_ brochure from the librarian in any villages for you to order goods from home (the available goods don't have to be the same as what the whole village is selling, it should be simply data-driven, with a default set of vanilla-ish goods, and customizable for modpack creators).

A few seconds after you placed your order, a nitwit with one llama or two, carrying all the things you bought will _magically_ spawn nearby and walk toward you. After the inventory was emptied, they'll despawn seconds later.

There's a cooldown between two purchases.

Killing any one of them causes the termination of service, you'll have to fight against another raid.

It can be an addon mod for Numismatic Overhaul if it sounds too off the goal. Should prolly go viral among RPG-themed modpack creators.

The more I describe it the more I think it's a bit too wild. So feel free to just close this.

**Comment by Noaaan** [comment]
I do kinda like this idea, but I do feel like it would definitely be better as its own mod. I would be interested to support it if it ever goes anywhere.
For now I will close this as not planned. Thanks for the suggestion though
