### ISSUE TITLE
Add Emi Support

### ISSUE THREAD

**Issue by Eatham532** [glisco03/numismatic-overhaul#76]
When using JEI I noticed that the items don't overlap the menu buttons. But when using EMI the items overlap. I was told that this mod had to add exclusion zones. Did send a message on discord, but I think it will be better to add it here.
https://github.com/emilyploszaj/emi

![image](https://user-images.githubusercontent.com/78714349/218371826-f0fbe6ee-10cb-466e-994e-eb7afd8f0f5b.png)

**Comment by Noaaan** [comment]
This is clearly not JEI, but that aside - EMI compat for exclusion zones in the creative inventory screen is a part of owo-lib, and not Numismatic Overhaul. Please open an issue there instead.
