### ISSUE TITLE
Crash when right clicking on a shop block.

### ISSUE THREAD

**Issue by snowjungsungwoo** [glisco03/numismatic-overhaul#77]
[1.txt](https://github.com/wisp-forest/numismatic-overhaul/files/10779698/1.txt)

**Comment by Dragon-Seeker** [comment]
Duplicate of #49, Install Charm Fixer: (https://www.curseforge.com/minecraft/mc-mods/charm-fixer) to fix the issue

**Comment by snowjungsungwoo** [comment]
ty:)
