### ISSUE TITLE
[1.19.2] Minecraft Comes Alive Incompatibility

### ISSUE THREAD

**Issue by DerKonigCleveland** [glisco03/numismatic-overhaul#78]
when loaded with MCA Reborn version 7.4.7 and 7.4.6 (haven't check another version) the game will crash on character making (after the world gen is finished and the mca logo appeared)

The loaded mod list is attached as a screenshot
![Screenshot 2023-03-05 181443](https://user-images.githubusercontent.com/88784075/222957177-f29d871b-9db5-49e0-9a16-d57840bb0973.png)

here is the link for the crash log: https://pastebin.pl/view/6dc9c605

**Comment by Noaaan** [comment]
This is a known issue which has already been fixed in the latest unreleased build of Numismatic Overhaul. It will be released soon:tm:.
In the meantime I recommend downgrading the version of Minecraft Comes Alive, since the older versions do not crash. Once we release the patch you should be able to update play with both the mods together without any issues. 

Do note that in the future versions, the items the villagers give you as tax is determined by MCA's config file, and **not** Numismatic Overhaul

**Comment by gliscowo** [comment]
This feature has now been removed from the mod in [0.2.9](https://modrinth.com/mod/numismatic-overhaul/version/W8o5cKwW) - as mentioned by @Noaaan you can now do this purely via MCA configuration

**Comment by PixelatedBruh** [comment]
backport to 1.19.2?

**Comment by bellakeys** [comment]
I have been trying to figure this out for a few days, and I'm stumped. What exactly should I do to get MCA:R (7.5.0, 1.19.2) and Numismatic (0.2.8, 1.19.2) working together? I tried updating the MCA config with each coin type & value, running it with MCA Compatibility both on and off, it crashes either way. Please advise!

**Comment by PixelatedBruh** [comment]
if you see this. i got it to work by deleting the mca compatibility class file and removing the mca mixin in the mixin data spot. its crude but it works

**Comment by LeDemmers** [comment]
> 



> if you see this. i got it to work by deleting the mca compatibility class file and removing the mca mixin in the mixin data spot. its crude but it works

Can you elaborate on how and what you did? As this is now the fix for everyone to use.

**Comment by PixelatedBruh** [comment]
sorry i didnt see this earlier. you have to open the jar in a program like 7zip (open archive) then navigate
com/glisco/numismaticoverhaul/mixin and delete the  class file labled mcacompat. Then navigate back to base directory. Open numismatic-overhaul.mixins.json. delete the one for mca. save and now it should work. sorry i wrote this on my phone as i was going to bed when i saw this.
