### ISSUE TITLE
Disable pillager drops

### ISSUE THREAD

**Issue by ryan-griffin** [glisco03/numismatic-overhaul#79]
Could a config option to disable pillager drops be added?

**Comment by Noaaan** [comment]
You are already able to change which mobs that drop c
oins via a datapack, as specified over at the documentation: https://docs.wispforest.io/numismatic-overhaul/home/#mob-drops This is the best solution as it allows for other mods to easiliy add integration in regards to which mobs drop money. 

I have provided an example datapack with this issue, which will override anything set in the tag, which disables coin drops entirely.  
It contains a copy of the tag, and you just have to [install it like normal.](https://minecraft.fandom.com/wiki/Tutorials/Installing_a_data_pack)

[no_bourgoisie.zip](https://github.com/wisp-forest/numismatic-overhaul/files/10952506/no_bourgoisie.zip)
