### ISSUE TITLE
Issue with players setting trades in the shop

### ISSUE THREAD

**Issue by FocusedVex** [glisco03/numismatic-overhaul#81]
I have Numismatic Overhaul on my Forge 1.18.2 server. Currently players are having issues in setting up trades in the shops they have crafted. I have also attempted to set a trade, however the input box for the trade item doesn't currently accept any items.

I am unsure of the reason, or if it is something we are doing wrong.

**Comment by BasiqueEvangelist** [comment]
This is the repository for Numismatic Overhaul on Fabric.

**Comment by Noaaan** [comment]
https://www.curseforge.com/minecraft/mc-mods/numismatic-overhaul-reforged
