### ISSUE TITLE
Players can't use admin shops with admin privileges 

### ISSUE THREAD

**Issue by AzrouStone** [glisco03/numismatic-overhaul#84]
Had a player un-opped try to use the shop, no gui appeared. gave them op and then the gui appeared. I have the shop at spawn and spawn is claimed using the FTB Chunks mod, if it is due to spawn protect in server properties or related to ftb let me know but otherwise it may be a glitch.

**Comment by gliscowo** [comment]
This is caused by FTB Chunks claim. If you want people to be able to use shops, you need to add the shop blocks to the `ftbchunks:interact_whitelist` block tag

Cheers
