### ISSUE TITLE
Money duplicates after death

### ISSUE THREAD

**Issue by JackoDEJ** [glisco03/numismatic-overhaul#86]
Money added to the purse from the inventory infinitely duplicates after dying. Game must be relaunched to fix this.

**Comment by gliscowo** [comment]
Can you give us more context on this issue? The way you reported it there's almost nothing we can do, as this issue quite obviously isn't that simple to reproduce with just Numismatic Overhaul alone

Please send us at the very least your `latest.log` file from the time this happened as well as a detailed description of how to reproduce this issue
Cheeres

**Comment by b0b4444** [comment]
I also have this issue. For more context, I have a big modpack and I had guessed it had something to do with the You're In Grave Danger mod. It only happens to me, the server OP, and not to the other player on my server. It happens every time I die, I get the message that money has been added to my wallet.

**Comment by gliscowo** [comment]
Can you reproduce the issue with only Numismatic Overhaul? If not, this is probably a problem with YIGD - in which case you'd need to report it on their repo instead
Cheers

**Comment by Noaaan** [comment]
This issue has not seen activity in quite a long time. AFAIK we haven't seen or heard any of it in later versions. If you are still experiencing this, feel free to re-open this issue, but for now I am closing this as stale.
