### ISSUE TITLE
[Request] The purse in creative mode menu

### ISSUE THREAD

**Issue by noawx** [glisco03/numismatic-overhaul#89]
It would be useful if the purse could be displayed in the "Survival Inventory" portion of the creative mode menu, because it is cumbersome to switch to survival mode and back to creative mode when mapmaking and testing.

**Comment by notIkibo** [comment]
Very true. Just as having no display while trading

**Comment by Noaaan** [comment]
We might look into doing this, as we are changing the purse to an owo-ui component, in order to make it be displayed in Villager Trade screen (see #54). With this in place adding it to the Creative inventory should in theory be possible

**Comment by notIkibo** [comment]
Will these changes also be available for 1.19.x? 1.20 is out now, but I don't think about switching yet

**Comment by Noaaan** [comment]
I do not believe so, as it depends on features exclusive to owo-lib 0.11.0+, which is only for 1.20.

**Comment by notIkibo** [comment]
I cri

**Comment by gliscowo** [comment]
This has now been implemented in [0.2.10](https://modrinth.com/mod/numismatic-overhaul/version/0.2.10+1.20)
Cheers
