### ISSUE TITLE
Config option to disable the purse

### ISSUE THREAD

**Issue by mageowl** [glisco03/numismatic-overhaul#91]
It would be cool if you could disable the coin purse in your inventory.

**Comment by gliscowo** [comment]
I'm somewhat puzzled as to why exactly this would be something you want to do - doing so would literally remove one of the core aspects of the mod and make it, like, really hard to use?

If you do want the purse gone for whatever reason, nothing is stopping you from just setting the coordinates in the config to a very large value to push it off the screen.

Either way, could you offer us some more insight?
Cheers

**Comment by mageowl** [comment]
Nevermind.
