### ISSUE TITLE
Request: Shop blocks buy items

### ISSUE THREAD

**Issue by katubug** [glisco03/numismatic-overhaul#92]
Hi! I'm not sure if you're still supporting 1.19.2 forge, but I was considering adding this to my modpack and one feature that we'd really like is the ability to buy items as well as selling them.

Ideally there would be an interface in the shop block that allows the owner to insert coins, and they would select the item to buy and at how much. Then, others could come by and sell their items for coinage from the shop block.

Is this something you'd be willing to consider? Thanks for your time!

**Comment by gliscowo** [comment]
For one, we do not maintain the Forge port of this mod - it is unofficial and, from we hear, horrifically buggy in quite a few areas. For your question regarding the Shop, however, we have an explanation of our sentiment in the [Wisp Forest FAQ](https://docs.wispforest.io/faq/#why-can-the-shop-not-buy-items)

Cheers

**Comment by katubug** [comment]
Ah, my apologies, I just googled and didn't realize. Thanks for your
response! I'll keep that in mind.
