### ISSUE TITLE
Can I port this mod to forge?

### ISSUE THREAD

**Issue by Xplodin** [glisco03/numismatic-overhaul#95]
Basically willing to either pay someone to port the mod or try at it myself.
I just need to ask, IF it does get ported, how should I go about adding to curseforge/modrinth? Can I upload it? Should I send the finished jar/code your way?

Love the mod, but fabric doesnt have what I need for a modpack. (RS, Mekanism, etc) and I see no alternatives for terraria like currency on forge. 

Also architectury I hear is nice for cross-modloader development

**Comment by Noaaan** [comment]
There is already an exsting fork of Numismatic Overhaul for Forge, released here: https://www.curseforge.com/minecraft/mc-mods/numismatic-overhaul-reforged

**Comment by Xplodin** [comment]
sorry for my blindness.
I had trouble finding one. but thank you for the link!
