### ISSUE TITLE
[Feature Request] Option to disable villager trading

### ISSUE THREAD

**Issue by Flagadar** [glisco03/numismatic-overhaul#99]
Hi!
First of all, thanks for your amazing work!
I am running a server with this mod, mainly for shops and the currency itself.
I was wondering if it was possible to keep the vanilla villager trades (with emeralds) and only keep the currency system and shops, mainly to avoid farming coins.
I know there are other economy mods but I really do like this mod and I'm planning to use owo for other things.
Maybe I should try to clone the mod and tinker with it myself? (i'm on 1.19.2 btw)
Thanks a lot!

**Comment by Noaaan** [comment]
There should already be a config option for this

**Comment by Flagadar** [comment]
Oh indeed sorry, I isn't indicated on the wiki and I didn't check in the config, thanks!
